# infrastructure.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      name: internal
    - port: 29093
      name: controller
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka:29093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092" # Nota: usiamo il nome del Service K8s
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          readinessProbe: # Kubernetes controllerà questo prima di mandare traffico
            exec:
              command: [ "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: datadb
spec:
  ports:
    - port: 3306
  selector:
    app: datadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadb
spec:
  selector:
    matchLabels:
      app: datadb
  template:
    metadata:
      labels:
        app: datadb
        network: data-net
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ermenegildo
            - name: MYSQL_DATABASE
              value: mysqldataDB
---
apiVersion: v1
kind: Service
metadata:
  name: userdb
spec:
  ports:
    - port: 3306
  selector:
    app: userdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
        network: user-net
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pasquale
            - name: MYSQL_DATABASE
              value: mysqluserDB