services:
  dataDB:
    image: mysql:latest
    container_name: dataDB
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ermenegildo
      - MYSQL_DATABASE=mysqldataDB
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dataNet

  userDB:
    image: mysql:latest
    container_name: userDB
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pasquale
      - MYSQL_DATABASE=mysqluserDB
    volumes:
      - ./mysql_user:/var/lib/mysql
    networks:
      - userNet


  data:   #gRPC client
    build: ./DataCollector
    container_name: dataCollector
    depends_on:
      - dataDB
    ports:
      - "5002:5000"
    environment:
      - TARGET_GRPC_HOST=userManager
      - TARGET_GRPC_PORT=50051
      - DB_HOST=dataDB
      - DB_NAME=mysqldataDB
      - MYSQL_ROOT_PASSWORD=ermenegildo
    networks:
      - dataNet
      - internalNet


  user:   #gRPC server
    build: ./UserManager
    container_name: userManager
    depends_on:
      - userDB
    ports:
      - "5001:5000"
    environment:
      - GRPC_PORT=50051
      - DB_HOST=userDB
      - DB_NAME=mysqluserDB
      - MYSQL_ROOT_PASSWORD=pasquale
    networks:
      - userNet
      - internalNet


networks:
  dataNet:
  userNet:
  internalNet:
    driver: bridge