services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  # Configurazione per chi ascolta, dove si connette e chi si deve connettere
      # 9092: Per i container (DataCollector, AlertSystem)
      # 29092: Per il locale (IntelliJ, Postman)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  # Configurazioni varie
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' # Crea automaticamente i topic
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - internalNet

  apigw:
    image: nginx
    container_name: gateway
    ports:
      - '8080:80'
    depends_on:
      - data
      - user
    environment:
      - JWT_SECRET=22d7bfbf2a5c1afc744f60f3af98c5b1f3b3e5699a88821882e175e4e01decfc
    volumes:
      - ./nginx/configs/routing.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dataNet
      - userNet

  dataDB:
    image: mysql:latest
    container_name: dataDB
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ermenegildo
      - MYSQL_DATABASE=mysqldataDB
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dataNet

  userDB:
    image: mysql:latest
    container_name: userDB
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pasquale
      - MYSQL_DATABASE=mysqluserDB
    volumes:
      - ./mysql_user:/var/lib/mysql
    networks:
      - userNet

  data:   #gRPC client
    build:
      context: .
      dockerfile: DataCollector/Dockerfile
    container_name: dataCollector
    depends_on:
      - dataDB
    ports:
      - "5002:5000"
    environment:
      - TARGET_GRPC_HOST=userManager
      - TARGET_GRPC_PORT=50051
      - DB_HOST=dataDB
      - DB_NAME=mysqldataDB
      - MYSQL_ROOT_PASSWORD=ermenegildo
      - PYTHONUNBUFFERED=1
    networks:
      - dataNet
      - internalNet

  user:   #gRPC server
    build:
      context: .
      dockerfile: UserManager/Dockerfile
    container_name: userManager
    depends_on:
      - userDB
    ports:
      - "5001:5000"
    environment:
      - GRPC_PORT=50051
      - DB_HOST=userDB
      - DB_NAME=mysqluserDB
      - MYSQL_ROOT_PASSWORD=pasquale
    networks:
      - userNet
      - internalNet

networks:
  dataNet:
  userNet:
  internalNet:
    driver: bridge