# --- USER MANAGER (gRPC Server) ---
apiVersion: v1
kind: Service
metadata:
  name: usermanager
spec:
  selector:
    app: usermanager
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanager
spec:
  selector:
    matchLabels:
      app: usermanager
  template:
    metadata:
      labels:
        app: usermanager
        network: user-net
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: [ 'sh', '-c', "until nc -z userdb 3306; do echo waiting for userdb; sleep 2; done" ]
      containers:
        - name: usermanager
          image: usermanager:v1
          imagePullPolicy: Never
          env:
            - name: GRPC_PORT
              value: "50051"
            - name: DB_HOST
              value: "userdb"         # Nome del Service K8s definito sopra
            - name: DB_NAME
              value: "mysqluserDB"
            - name: MYSQL_ROOT_PASSWORD
              value: "pasquale"
# --- DATA COLLECTOR (gRPC Client) ---
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
spec:
  selector:
    app: datacollector
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacollector
spec:
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
        network: data-net
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z datadb 3306; do echo waiting for datadb; sleep 2; done;
              until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;
      containers:
        - name: datacollector
          image: datacollector:v1
          imagePullPolicy: Never
          env:
            - name: data-node
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TARGET_GRPC_HOST
              value: "usermanager"
            - name: TARGET_GRPC_PORT
              value: "50051"
            - name: DB_HOST
              value: "datadb"
            - name: DB_NAME
              value: "mysqldataDB"
            - name: KAFKA_HOST # Se serve al data collector
              value: "kafka:9092"
            - name: MYSQL_ROOT_PASSWORD
              value: "ermenegildo"
          ports:
            - containerPort: 5000
            - containerPort: 8000
# --- ALERT SYSTEM ---
---
apiVersion: v1
kind: Service
metadata:
  name: alertsystem
spec:
  selector:
    app: alertsystem
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsystem
spec:
  selector:
    matchLabels:
      app: alertsystem
  template:
    metadata:
      labels:
        app: alertsystem
        network: data-net
    spec:
      initContainers:
        - name: wait-for-kafka-db
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;
              until nc -z datadb 3306; do echo waiting for datadb; sleep 2; done;
      containers:
        - name: alertsystem
          image: alertsystem:v1
          imagePullPolicy: Never
          env:
            - name: alert-node
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KAFKA_HOST
              value: "kafka:9092"
            - name: INPUT_TOPIC
              value: "to-alert-system"
            - name: OUTPUT_TOPIC
              value: "to-notifier"
            - name: DB_HOST
              value: "datadb"
            - name: DB_NAME
              value: "mysqldataDB"
            - name: MYSQL_ROOT_PASSWORD
              value: "ermenegildo"
          ports:
            - containerPort: 5000
            - containerPort: 8000
# --- ALERT NOTIFIER ---
---
apiVersion: v1
kind: Service
metadata:
  name: alertnotifier
spec:
  selector:
    app: alertnotifier
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertnotifier
spec:
  selector:
    matchLabels:
      app: alertnotifier
  template:
    metadata:
      labels:
        app: alertnotifier
        network: data-net
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;
      containers:
        - name: alertnotifier
          image: alertnotifier:v1
          imagePullPolicy: Never
          env:
            - name: KAFKA_HOST
              value: "kafka:9092"
            - name: INPUT_TOPIC
              value: "to-notifier"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GMAIL_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GMAIL_APP_PASSWORD

# --- SLA BREACH DETECTOR ---
---
apiVersion: v1
kind: Service
metadata:
  name: sladetector
spec:
  selector:
    app: sladetector
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sladetector
spec:
  replicas: 1 # IMPORTANTE: Solo 1 istanza
  selector:
    matchLabels:
      app: sladetector
  template:
    metadata:
      labels:
        app: sladetector
        network: data-net # Lo mettiamo nella stessa rete dei dati per vedere Kafka/Prometheus
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;
              until nc -z prometheus 9090; do echo waiting for prometheus; sleep 2; done;
      containers:
        - name: sladetector
          image: sladetector:v1
          imagePullPolicy: Never
          env:
            - name: KAFKA_HOST
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "sla-breach-topic"
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090" # Nome del Service Prometheus definito in prometheus-k8s.yaml
            - name: CHECK_INTERVAL
              value: "20"
          ports:
            - containerPort: 5000