# 1. BLOCCO CONNESSIONI
# Nessun pod può ricevere traffico se non esplicitamente permesso.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
# 2. RETE DATA
# Permette il traffico tra i pod etichettati come 'network: data-net'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-data-net
spec:
  podSelector:
    matchLabels:
      network: data-net
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network: data-net
      ports:
        - port: 3306 # MySQL
        - port: 5000 # App Internal Port
        - port: 9092
        - port: 29093
        - port: 8000 # Prometheus server interno

---
# 3. RETE USER
# Permette il traffico tra i pod etichettati come 'network: user-net'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-user-net
spec:
  podSelector:
    matchLabels:
      network: user-net
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network: user-net
      ports:
        - port: 3306 # MySQL

---
# 4. ACCESSO INGRESS (Dal mondo esterno ai servizi)
# Permette al controller Ingress di chiamare le API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-traffic
spec:
  podSelector:
    matchExpressions:
      - {key: app, operator: In, values: [usermanager, datacollector]}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 5000
---
# 5. PONTE gRPC (DataCollector -> UserManager)
# Eccezione alla separazione delle reti: permette al DataCollector di chiamare via gRPC lo UserManager.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grpc-data-to-user
spec:
  podSelector:
    matchLabels:
      app: usermanager # La regola si applica alla destinazione (Server)
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: datacollector # La sorgente autorizzata (Client)
      ports:
        - protocol: TCP
          port: 50051
---
# 6. ACCESSO PROMETHEUS ESTERNO
# Permette di accedere alla dashboard di Prometheus (porta 9090) da fuori il cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-external
spec:
  podSelector:
    matchLabels:
      app: prometheus
  ingress:
    - ports:
        - port: 9090