server {
    listen 80;
#DataCollector
    location /add {
        proxy_pass http://data:5000;
    }
    location /view_interests {
        proxy_pass http://data:5000;
    }
    location /delete_interest {
        proxy_pass http://data:5000;
    }
    location /get_data {
        proxy_pass http://data:5000;
    }
    location /view_flights {
        proxy_pass http://data:5000;
    }
    location /last_flights {
        proxy_pass http://data:5000;
    }
    location /avg_flights {
        proxy_pass http://data:5000;
    }
    location /mod_pref {
        proxy_pass http://data:5000;
    }
#UserManager
    location /new {
        proxy_pass http://user:5000;
    }
    location /delete {
        proxy_pass http://user:5000;
    }

#SLABreachDetector
    location /sla {
        proxy_pass http://slaDetector:5000;
    }
}